export default {
    audioURL: 'https://firebasestorage.googleapis.com/v0/b/leerly.appspot.com/o/audios%2FManipulacio%CC%81n%20y%20nutricio%CC%81n.mp3?alt=media&token=1e24a3fc-0a9b-4118-8a7c-36817147cb3f',
    article: `En la actualidad, con el auge de las dietas veganas o de la popularidad de los gimnasios, la salud, tanto física como alimenticia, parece haberse convertido en un tema crucial de nuestro día a día, especialmente para las clases media y alta. Además, con el aumento de la información accesible acerca de la salud física o nutricional en internet, la gente parece haber asimilado que su salud es responsabilidad suya. Es más, existe la creencia generalizada de que sabemos a ciencia cierta lo que nos conviene y lo que no. Pero, ¿y si la información disponible hubiese sido manipulada?

    En 2015, el New York Times publicó un artículo en el que revelaba que Coca cola había estado secretamente financiando la Red Global de Balance Energético, en la Universidad de Colorado. Esta red de investigación tenía como objetivo la difusión del mensaje de que todas las calorías son iguales; más concretamente, defendía que el azúcar de los refrescos era igual de perjudicial para la salud que el azúcar de cualquier otro alimento o que la falta de ejercicio físico.
    
    No es la primera vez que este tipo de estrategia se usa para la venta de productos de dudoso beneficio para el consumidor. Entre estos productos se incluyen el tabaco, el alcohol y algunos tipos de medicamentos. Gyorgy Scrinis, profesor adjunto de políticas alimentarias en la Universidad de Melbourne, se refiere a este tipo de estrategias como “actividades científicas corporativas”. Dentro de estas actividades incluye “la financiación y realización de investigaciones nutricionales internas relacionadas con sus productos; el patrocinio de seminarios científicos y reuniones de expertos; la participación en comités de normas y políticas científicas; la publicación en revistas académicas; la financiación de grupos de fachada científicos; y la ejecución de programas de educación nutricional.
    
    Por medio de estas estrategias de manipulación, las empresas están creando una concepción general falsa de la comida y de su efecto en nuestro cuerpo. Por tanto, Scrinis cree necesaria la concienciación de las personas sobre estas estrategias con el fin de retomar el control sobre nuestra propia salud.`,
}