export default {
    Primary: '#1f4ab8',
    Green: '#47b379',
    DarkerGreen: '#2d9c4b',
    LightGrey: '#eee', 
    MediumGrey: '#666',
    ArticleTypes: {
        background: {
            'business': '#e1ccff',
            'art': '#cfe4ff',
            'technology': '#e1ccff',
            'nature': '#dcffd4',
            'science': '#dcffd4',
            'opinion': '#cfe4ff',
            'fiction': '#ffffd1',
            'religion': '#ffffd1',
            'politics': '#e1ccff',
            'self-help': '#ffffd1',
            'culture': '#cfe4ff',
            'history': '#cfe4ff',
            'latin-america': '#ffd7c2',
            'spain': '#ffd7c2',
        },
        copy: {
            'business': '#5611b8',
            'art': '#124c94',
            'technology': '#5611b8',
            'nature': '#1c7508',
            'science': '#1c7508',
            'opinion': '#124c94',
            'fiction': '#665800',
            'religion': '#665800',
            'politics': '#5611b8',
            'self-help': '#665800',
            'culture': '#124c94',
            'history': '#124c94',
            'latin-america': '#8a3000',
            'spain': '#8a3000',
        }
    }
}
